### ISSUE TITLE
[Automate] Integrate automated quality analysis

### ISSUE THREAD

**Issue by ClaireDH3** [AdrienZianne/calculator-cucumber-2025#20]
**Issue** 

- [x] Run an automated quality analysis checker for analysing the quality of the code (such as SonarLint or its cloud-based or CI-based version).

- [x] Add a badge in the README file to report on this quality.

- [ ] Add CI/CD support (GitHub Actions) to do this upon every new code commit (or pull request?)

**Classification**
quality improvement

**Comment by AdrienZianne** [comment]
We need to use that
**Badge :**
```html
<properties>
  <sonar.organization>adrienziannelegrandinquisiteurbackend</sonar.organization>
  <sonar.host.url>https://sonarcloud.io</sonar.host.url>
</properties>
```
**Workflow :**
```yml
name: SonarQube
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu' # Alternative distribution options are available.
      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=AdrienZianne_calculator-cucumber-2025
```
